# Generated by Django 2.0.6 on 2018-06-03 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='meeting date')),
                ('category', models.CharField(choices=[('u', 'MOE U'), ('b', 'Build'), ('e', 'Non-mandatory'), ('o', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SignIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateTimeField(verbose_name='student birthday')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='signin',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='students',
            field=models.ManyToManyField(through='attendance.SignIn', to='attendance.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='signin',
            unique_together={('meeting_id', 'student_id')},
        ),
    ]
