# Generated by Django 2.0.6 on 2018-06-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20180603_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subteam',
            field=models.CharField(choices=[('m', 'Mechanical'), ('e', 'Electrical'), ('p', 'Programming'), ('d', 'Media')], default='e', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(choices=[('u', 'MOE U'), ('b', 'Build'), ('n', 'Non-mandatory'), ('o', 'Other')], max_length=1),
        ),
    ]
